### ISSUE TITLE
Model instance fields not readable from model instance methods

### ISSUE THREAD

**Issue by ahutchings** [tomasz-zablocki/redux-orm-types#20] opened 2019-09-03 17:34 UTC
The fields of a model are not available to methods defined on that model.

For example, in the following snippet, reading the `title` field from an instance method reports a TypeScript error:

```typescript
interface BookFields {
  title: string
}

class Book extends Model<typeof Book, BookFields> {
  ...

  getTitle() {
    // Property 'title' does not exist on type 'Book'. ts(2339) 
    return this.title;
  }
}
```

**Comment by tomasz-zablocki** [comment] 2019-09-05 11:40
Obviously for the `title` to be recognized in `getTitle()` body it would have to be a property of `Book` class. It was one of my attempts to do it this way, however `babel` transpilation has a bug that results in different output then the one of `tsc`, effectively breaking `redux-orm` in typescript projects transpiled using babel, for instance `create-react-app`.

You can workaround this shortcoming by hinting `this` type to a particular method: 

```typescript
interface BookFields {
  title: string
}

class Book extends Model<typeof Book, BookFields> {
  ...
  // special typescript syntax to override type of this inside given method
  getTitle(this: BookFields) { 
 
    return this.title;
  }
}
```

FYI, type declarations for the upcoming **redux-orm** version won't need such workaround, since they use declaration merging. This is a breaking change so it will have to wait until the next library release. 

Let me know if this solves your problem.

**Comment by ahutchings** [comment] 2019-09-05 16:02
Thanks for your prompt reply. I tried hinting `this` for methods reading from fields, and it works for some cases, but breaks others that expect `this` to include all class methods/properties. I was able to work around that with a slight modification to your suggestion. This resolves most of my errors.

```typescript
interface Fields {
 ...
}

type This<T> = T & Fields;

class Node extends Model<typeof Node, Fields>
  /**
   * Removes the child with the given id.
   * @returns {this}
   */
  public removeChildById(this: This<this>, childId: number): this {
    this.children.remove(childId);
    return this;
  }
}
```

I am still having trouble with the typing for `this.ref`, but need to investigate that further to understand why.

Regarding the `babel` transpilation difference, I did some investigation into what I believe is the issue you're talking about, and found that TS is not conforming to the class properties spec. There has been [some discussion on the TypeScript repo](https://github.com/microsoft/TypeScript/issues/12437#issuecomment-356757028) around whether TS should change that behavior in a breaking release. 

**Update**

I found a better way to achieve the same thing with declaration merging. This doesn't require hinting `this` for public methods accessing fields.

```typescript
interface Fields {
 ...
}

interface Node extends Fields {}

class Node extends Model<typeof Node, Fields>
  /**
   * Removes the child with the given id.
   * @returns {this}
   */
  public removeChildById(childId: number): this {
    this.children.remove(childId);
    return this;
  }
}
```

**Comment by ahutchings** [comment] 2019-09-05 17:57
Is it possible to publish prerelease versions of typings using DefinitelyTyped or some other mechanism? I'd like to upgrade to the latest v0.14 release candidate of redux-orm if I can use the declaration-merging-based typings solution with it.

**Comment by tomasz-zablocki** [comment] 2019-09-06 12:30
@ahutchings love the approach you've added in the update, great find.

Regarding the first solution:

> ```ts
> interface Fields {
>  ...
> }
> 
> type This<T> = T & Fields;
> 
> class Node extends Model<typeof Node, Fields>
>   /**
>    * Removes the child with the given id.
>    * @returns {this}
>    */
>   public removeChildById(this: This<this>, childId: number): this {
>     this.children.remove(childId);
>     return this;
>   }
> }
> ```

Instead of `type This<T>` you can use `SessionBoundModel<M extends Model>` but your declaration merging approach is likely better.

> I am still having trouble with the typing for `this.ref`, but need to investigate that further to understand why.

Current typing for `ref` is shoddy, but I hadn't found a way to improve it without reworking types to declaration merging. Let me know what is your issue, I'll be happy to help as much as I can.

> Regarding the `babel` transpilation difference, I did some investigation into what I believe is the issue you're talking about, and found that TS is not conforming to the class properties spec. There has been [some discussion on the TypeScript repo](https://github.com/microsoft/TypeScript/issues/12437#issuecomment-356757028) around whether TS should change that behavior in a breaking release.

Yes, this is the related behavior and the cause of the problem. Took me days of debugging `redux-orm` to figure it out.

Regarding v0.14 types, they are not complete yet. Specifically, the new selector API is missing. 
They can't be published to DefTyped, but you can try them out. 

I've created a [repo](https://github.com/tomasz-zablocki/redux-orm-ex-types-react-example) which is basically an example of using the types without the pain involved in customized type resolution. You'll have to change `experimental` to `v0.14-beta` when pointing to `redux-orm-types` dependency in package.json.

Please keep in mind that while v0.14 types are much cleaner and better organized then the present version, this is a work in progress and some things might not work. I've been mostly focused on reducing complexity and there are some major gains in terms of how many types are generated, which will probably improve overall IDE experience.

Let me know if you run into troubles using v0.14-beta.

**Comment by tomasz-zablocki** [comment] 2019-09-10 14:12
@ahutchings, can I close this or is there something that requires clarifying ?

I've created a [gist](https://gist.github.com/tomasz-zablocki/253db756b5032c09c04adff281f4c2b8) to preserve your solution, hope you don't mind.

**Closed as completed** 2019-09-10 14:21 UTC
Labels: wontfix

**Comment by ahutchings** [comment] 2019-09-10 15:35
This is fine to close. I will use the latest v0.14 beta of redux-orm and typings as many of my issues seem to be addressed there. Thanks for your help!
